# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e62cdfdce999a838bc944e51c01614be9abe75f697a244fd99edf999e3c43dcc9500e3308ab5af4867ba76447d083ca4b4d6f5211ff4ecdc59cf33a3fcac1d41

test:
  secret_key_base: 71026100643afa58ae9646daa9afeb94283ae5a697dcc4777fe1d1e91084372ad3548ef4dea513ec7dd344bbe72c84b561ec53ef2c3f23cb216c9fd917250132

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
